path:
  data_root: null
  data_temp: null
  server_data: null
  # TODO: need to add additional options for server communications
db:
  engine: postgresql
  user: postgres
  password: fragile
  host: localhost
  port: 5432
  database: seechange

storage:
  images:
    single_file: false
