"""image_fourcorners

Revision ID: b33a5b72da8b
Revises: e78c1e8bec33
Create Date: 2023-09-07 19:27:39.774329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33a5b72da8b'
down_revision = 'e78c1e8bec33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('ra00', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('ra01', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('ra10', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('ra11', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec00', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec01', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec10', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec11', sa.REAL(), nullable=False))
    op.create_index(op.f('ix_images_dec00'), 'images', ['dec00'], unique=False)
    op.create_index(op.f('ix_images_dec01'), 'images', ['dec01'], unique=False)
    op.create_index(op.f('ix_images_dec10'), 'images', ['dec10'], unique=False)
    op.create_index(op.f('ix_images_dec11'), 'images', ['dec11'], unique=False)
    op.create_index(op.f('ix_images_ra00'), 'images', ['ra00'], unique=False)
    op.create_index(op.f('ix_images_ra01'), 'images', ['ra01'], unique=False)
    op.create_index(op.f('ix_images_ra10'), 'images', ['ra10'], unique=False)
    op.create_index(op.f('ix_images_ra11'), 'images', ['ra11'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_ra11'), table_name='images')
    op.drop_index(op.f('ix_images_ra10'), table_name='images')
    op.drop_index(op.f('ix_images_ra01'), table_name='images')
    op.drop_index(op.f('ix_images_ra00'), table_name='images')
    op.drop_index(op.f('ix_images_dec11'), table_name='images')
    op.drop_index(op.f('ix_images_dec10'), table_name='images')
    op.drop_index(op.f('ix_images_dec01'), table_name='images')
    op.drop_index(op.f('ix_images_dec00'), table_name='images')
    op.drop_column('images', 'dec11')
    op.drop_column('images', 'dec10')
    op.drop_column('images', 'dec01')
    op.drop_column('images', 'dec00')
    op.drop_column('images', 'ra11')
    op.drop_column('images', 'ra10')
    op.drop_column('images', 'ra01')
    op.drop_column('images', 'ra00')
    # ### end Alembic commands ###
