"""update_instrument

Revision ID: 8901dcec579d
Revises: 707ce0827b45
Create Date: 2023-08-29 20:07:36.185209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8901dcec579d'
down_revision = '707ce0827b45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposures', sa.Column('origin_identifier', sa.Text(), nullable=True))
    op.drop_index('ix_exposures_telescope', table_name='exposures')
    op.create_index(op.f('ix_exposures_origin_identifier'), 'exposures', ['origin_identifier'], unique=False)
    op.drop_column('exposures', 'telescope')
    op.drop_column('sensor_sections', 'gain')
    op.drop_column('sensor_sections', 'non_linearity_limit')
    op.drop_column('sensor_sections', 'dark_current')
    op.drop_column('sensor_sections', 'read_noise')
    op.drop_column('sensor_sections', 'saturation_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_sections', sa.Column('saturation_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_sections', sa.Column('read_noise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_sections', sa.Column('dark_current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_sections', sa.Column('non_linearity_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_sections', sa.Column('gain', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exposures', sa.Column('telescope', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_exposures_origin_identifier'), table_name='exposures')
    op.create_index('ix_exposures_telescope', 'exposures', ['telescope'], unique=False)
    op.drop_column('exposures', 'origin_identifier')
    # ### end Alembic commands ###
