"""zeropoint_in_zerpoint

Revision ID: 6cabf4251810
Revises: 406abb705c55
Create Date: 2023-11-13 17:41:03.697416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cabf4251810'
down_revision = '406abb705c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zero_points', sa.Column('zp', sa.Float(), nullable=False))
    op.add_column('zero_points', sa.Column('dzp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zero_points', 'dzp')
    op.drop_column('zero_points', 'zp')
    # ### end Alembic commands ###
