"""zeropoint_in_zeropoint

Revision ID: 637eb690f408
Revises: a9c1d480a229
Create Date: 2023-11-08 21:28:33.886444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637eb690f408'
down_revision = 'a9c1d480a229'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zero_points', sa.Column('zp', sa.Float(), nullable=False))
    op.add_column('zero_points', sa.Column('dzp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zero_points', 'dzp')
    op.drop_column('zero_points', 'zp')
    # ### end Alembic commands ###
