"""fix_psf_typo

Revision ID: 792155bc3933
Revises: a2d0167cd287
Create Date: 2024-08-02 17:09:25.159417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792155bc3933'
down_revision = 'a2d0167cd287'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_upstreams_association_upstream_id_fkey', 'image_upstreams_association', type_='foreignkey')
    op.create_foreign_key('image_upstreams_association_upstream_id_fkey', 'image_upstreams_association', 'images', ['upstream_id'], ['id'], ondelete='RESTRICT')
    op.add_column('psfs', sa.Column('sources_id', sa.UUID(), nullable=False))
    op.drop_index('ix_psfs_source_id', table_name='psfs')
    op.create_index(op.f('ix_psfs_sources_id'), 'psfs', ['sources_id'], unique=True)
    op.drop_constraint('psfs_source_lists_id_fkey', 'psfs', type_='foreignkey')
    op.create_foreign_key('psfs_source_lists_id_fkey', 'psfs', 'source_lists', ['sources_id'], ['id'], ondelete='CASCADE')
    op.drop_column('psfs', 'source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psfs', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('psfs_source_lists_id_fkey', 'psfs', type_='foreignkey')
    op.create_foreign_key('psfs_source_lists_id_fkey', 'psfs', 'source_lists', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_psfs_sources_id'), table_name='psfs')
    op.create_index('ix_psfs_source_id', 'psfs', ['source_id'], unique=False)
    op.drop_column('psfs', 'sources_id')
    op.drop_constraint('image_upstreams_association_upstream_id_fkey', 'image_upstreams_association', type_='foreignkey')
    op.create_foreign_key('image_upstreams_association_upstream_id_fkey', 'image_upstreams_association', 'images', ['upstream_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
