"""test removing header_excerpt

Revision ID: cd42ac60576e
Revises: c25e4f33cfaa
Create Date: 2024-05-21 17:04:15.577156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd42ac60576e'
down_revision = 'c25e4f33cfaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_coordinates', 'header_excerpt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_coordinates', sa.Column('header_excerpt', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
