"""refset_remove_upstream_hash

Revision ID: ab909c1699d4
Revises: a32a30407971
Create Date: 2024-08-12 21:06:38.156612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab909c1699d4'
down_revision = 'a32a30407971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refsets_upstream_hash', table_name='refsets')
    op.drop_column('refsets', 'upstream_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refsets', sa.Column('upstream_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_refsets_upstream_hash', 'refsets', ['upstream_hash'], unique=False)
    # ### end Alembic commands ###
