"""knowexposures

Revision ID: 6e83953ecf35
Revises: f36d17393be7
Create Date: 2024-06-04 13:23:01.387331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e83953ecf35'
down_revision = 'f36d17393be7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knownexposures',
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exposure_id', sa.BigInteger(), nullable=True),
    sa.Column('mjd', sa.Double(), nullable=True),
    sa.Column('exp_time', sa.REAL(), nullable=True),
    sa.Column('filter', sa.Text(), nullable=True),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Text(), nullable=True),
    sa.Column('claim_time', sa.DateTime(), nullable=True),
    sa.Column('ra', sa.Double(), nullable=True),
    sa.Column('dec', sa.Double(), nullable=True),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures.id'], name='knownexposure_exposure_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knownexposures_created_at'), 'knownexposures', ['created_at'], unique=False)
    op.create_index(op.f('ix_knownexposures_ecllat'), 'knownexposures', ['ecllat'], unique=False)
    op.create_index(op.f('ix_knownexposures_gallat'), 'knownexposures', ['gallat'], unique=False)
    op.create_index(op.f('ix_knownexposures_id'), 'knownexposures', ['id'], unique=False)
    op.create_index(op.f('ix_knownexposures_instrument'), 'knownexposures', ['instrument'], unique=False)
    op.create_index(op.f('ix_knownexposures_mjd'), 'knownexposures', ['mjd'], unique=False)
    op.create_index('knownexposures_q3c_ang2ipix_idx', 'knownexposures', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('knownexposures_q3c_ang2ipix_idx', table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_mjd'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_instrument'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_id'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_gallat'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_ecllat'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_created_at'), table_name='knownexposures')
    op.drop_table('knownexposures')
    # ### end Alembic commands ###
