"""Naive add fileOnDiskMixin to WCS

Revision ID: c25e4f33cfaa
Revises: 573289f12368
Create Date: 2024-05-10 16:26:27.952262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c25e4f33cfaa'
down_revision = '573289f12368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cutouts_q3c_ang2ipix_idx', table_name='cutouts')
    op.drop_index('exposure_q3c_ang2ipix_idx', table_name='exposures')
    op.drop_index('images_q3c_ang2ipix_idx', table_name='images')
    op.drop_index('measurements_q3c_ang2ipix_idx', table_name='measurements')
    op.add_column('world_coordinates', sa.Column('filepath_extensions', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('world_coordinates', sa.Column('md5sum', sa.UUID(), nullable=True))
    op.add_column('world_coordinates', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.add_column('world_coordinates', sa.Column('filepath', sa.Text(), nullable=False))
    op.create_index(op.f('ix_world_coordinates_filepath'), 'world_coordinates', ['filepath'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_coordinates_filepath'), table_name='world_coordinates')
    op.drop_column('world_coordinates', 'filepath')
    op.drop_column('world_coordinates', 'md5sum_extensions')
    op.drop_column('world_coordinates', 'md5sum')
    op.drop_column('world_coordinates', 'filepath_extensions')
    op.create_index('measurements_q3c_ang2ipix_idx', 'measurements', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    op.create_index('images_q3c_ang2ipix_idx', 'images', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    op.create_index('exposure_q3c_ang2ipix_idx', 'exposures', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    op.create_index('cutouts_q3c_ang2ipix_idx', 'cutouts', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    # ### end Alembic commands ###
