"""more_measurements_changes

Revision ID: 47c13a1dc1d1
Revises: 319afe5e8ee8
Create Date: 2025-01-21 18:37:03.531008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c13a1dc1d1'
down_revision = '319afe5e8ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('psf_fit_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'psf_fit_failed')
    # ### end Alembic commands ###
