"""measurements_modification

Revision ID: 196046be64a5
Revises: ba5f61f8d419
Create Date: 2025-01-15 21:47:33.795323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '196046be64a5'
down_revision = 'ba5f61f8d419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('x', sa.Integer(), nullable=False))
    op.add_column('measurements', sa.Column('y', sa.Integer(), nullable=False))
    op.add_column('measurements', sa.Column('centroid_x', sa.REAL(), nullable=False))
    op.add_column('measurements', sa.Column('centroid_y', sa.REAL(), nullable=False))
    op.drop_column('measurements', 'bkg_std')
    op.drop_column('measurements', 'offset_x')
    op.drop_column('measurements', 'offset_y')
    op.drop_column('measurements', 'bkg_pix')
    op.drop_column('measurements', 'bkg_mean')
    op.drop_column('measurements', 'area_psf')
    op.drop_column('measurements', 'area_apertures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('area_apertures', postgresql.ARRAY(sa.REAL()), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('area_psf', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('bkg_mean', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('bkg_pix', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('offset_y', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('offset_x', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('bkg_std', sa.REAL(), autoincrement=False, nullable=False))
    op.drop_column('measurements', 'centroid_y')
    op.drop_column('measurements', 'centroid_x')
    op.drop_column('measurements', 'y')
    op.drop_column('measurements', 'x')
    # ### end Alembic commands ###
