"""more_measurements_changes

Revision ID: 54fc36d9095d
Revises: 47c13a1dc1d1
Create Date: 2025-01-21 18:54:50.312002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fc36d9095d'
down_revision = '47c13a1dc1d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('psf_fit_flags', sa.Integer(), nullable=True))
    op.drop_column('measurements', 'psf_fit_failed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('psf_fit_failed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('measurements', 'psf_fit_flags')
    # ### end Alembic commands ###
