"""more_meas_mod

Revision ID: 24b76272e341
Revises: 0cd2cbdecf96
Create Date: 2025-01-17 18:14:24.265345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b76272e341'
down_revision = '0cd2cbdecf96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('major_width', sa.REAL(), nullable=False))
    op.add_column('measurements', sa.Column('minor_width', sa.REAL(), nullable=False))
    op.drop_index('ix_measurements_width', table_name='measurements')
    op.create_index(op.f('ix_measurements_major_width'), 'measurements', ['major_width'], unique=False)
    op.create_index(op.f('ix_measurements_minor_width'), 'measurements', ['minor_width'], unique=False)
    op.drop_column('measurements', 'elongation')
    op.drop_column('measurements', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('width', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('elongation', sa.REAL(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_measurements_minor_width'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_major_width'), table_name='measurements')
    op.create_index('ix_measurements_width', 'measurements', ['width'], unique=False)
    op.drop_column('measurements', 'minor_width')
    op.drop_column('measurements', 'major_width')
    # ### end Alembic commands ###
