"""more_meas_stuff

Revision ID: 32c832f52048
Revises: 24b76272e341
Create Date: 2025-01-17 19:46:30.682614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c832f52048'
down_revision = '24b76272e341'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('gfit_x', sa.REAL(), nullable=False))
    op.add_column('measurements', sa.Column('gfit_y', sa.REAL(), nullable=False))
    op.drop_column('measurements', 'centroid_x')
    op.drop_column('measurements', 'centroid_y')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('centroid_y', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('measurements', sa.Column('centroid_x', sa.REAL(), autoincrement=False, nullable=False))
    op.drop_column('measurements', 'gfit_y')
    op.drop_column('measurements', 'gfit_x')
    # ### end Alembic commands ###
