"""object_naming

Revision ID: b80115874d51
Revises: 8a9305b0daca
Create Date: 2025-03-04 15:00:57.881739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80115874d51'
down_revision = '8a9305b0daca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_name_max_used',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('maxnum', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object_name_max_used')
    # ### end Alembic commands ###
