---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive
  namespace: ls4-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-archive
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        nersc.gov/collab_uids: "103988"
        nersc.gov/gid: "103988"
        nersc.gov/gids: 10389,96414
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      labels:
        workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-archive
    spec:
      containers:
      - env:
        - name: CONNECTOR_READ_STORAGE
          value: /storage_ro
        - name: CONNECTOR_WRITE_STORAGE
          value: /storage
        - name: CONNECTOR_SECRETS
          value: /secrets
        image: registry.nersc.gov/m4616/nersc-upload-connector:raknop
        imagePullPolicy: Always
        name: archive
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: nersc-connector-secrets
        - mountPath: /storage_ro
          name: nersc-connector-storage-ro
        - mountPath: /storage
          name: nersc-connector-storage
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 103988
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: nersc-connector-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: nersc-connector-secrets
      - hostPath:
          # /dvs_ro doesn't work on spin
          # path: /dvs_ro/cfs/cdirs/m4616/archive-rknop-dev
          path: /global/cfs/cdirs/m4616/archive-rknop-dev
          type: Directory
        name: nersc-connector-storage-ro
      - hostPath:
          path: /global/cfs/cdirs/m4616/archive-rknop-dev
          type: Directory
        name: nersc-connector-storage
---
apiVersion: v1
kind: Service
metadata:
  name: archive
  namespace: ls4-rknop-dev
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-archive
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: archive-ingress
  namespace: ls4-rknop-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-archive
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archive
  namespace: ls4-rknop-dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
spec:
  rules:
  - host: archive.ls4-rknop-dev.production.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: archive-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: ls4-rknop-dev-archive.lbl.gov
    http:
      paths:
      - backend:
          service:
            name: archive-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ls4-rknop-dev-archive.lbl.gov
    secretName: ls4-rknop-dev-archive-cert
---
