---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor
  namespace: ls4-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-conductor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        nersc.gov/collab_uids: "103988"
        nersc.gov/gid: "103988"
        nersc.gov/gids: 10388,96414
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      labels:
        workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-conductor
    spec:
      containers:
      - image: registry.nersc.gov/m4616/seechange:conductor-rknop-dev
        imagePullPolicy: Always
        name: conductor
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /sessions
          name: conductor-sessions
        - mountPath: /secrets
          name: conductor-secrets
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: conductor-sessions
        persistentVolumeClaim:
          claimName: conductor-sessions-rknop-dev-20240612
      - name: conductor-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: conductor-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: conductor
  namespace: ls4-rknop-dev
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-conductor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: conductor-ingress
  namespace: ls4-rknop-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-conductor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conductor
  namespace: ls4-rknop-dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
spec:
  rules:
  - host: conductor.ls4-rknop-dev.production.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: conductor-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: ls4-conductor-rknop-dev.lbl.gov
    http:
      paths:
      - backend:
          service:
            name: conductor-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ls4-dev-conductor-rknop-dev.lbl.gov
    secretName: ls4-rknop-dev-conductor-cert
---
