apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-rknop-dev-20240502
  namespace: ls4-rknop-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
