apiVersion: v1
stringData:
  seechange_webap_config.py: |
    import pathlib
    PG_HOST = 'ls4db.lbl.gov'
    PG_PORT = 5432
    PG_USER = 'seechange_rknop_dev'
    PG_PASS = PUT THE RIGHT THING HERE
    PG_NAME = 'seechange_rknop_dev'
    ARCHIVE_DIR = pathlib.Path( '/archive/base' )
kind: Secret
metadata:
  name: webap-secrets
  namespace: ls4-rknop-dev
type: Opaque
