---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-webap
  name: webap
  namespace: ls4-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-webap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        nersc.gov/collab_uids: "103988"
        nersc.gov/gid: "63477"
        nersc.gov/gids: 63477,96414
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      labels:
        workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-webap
    spec:
      containers:
      - image: registry.nersc.gov/m4616/seechange-webap:rknop-dev_20250703
        imagePullPolicy: Always
        name: seechange-webap
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: webap-secrets
        - mountPath: /sessions
          name: webap-sessions
        - mountPath: /archive
          name: seechange-archive-dir
        # Comment the next four lines out to use the code baked into the Dockerfile
        - mountPath: /seechange
          name: seechange-install
        - mountPath: /webap_code
          name: seechange-webap-code
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 103988
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: webap-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: webap-secrets
      - name: webap-sessions
        persistentVolumeClaim:
          claimName: webap-sessions-pvc
      - name: seechange-webap-code
        hostPath:
          # path: /global/cfs/cdirs/m4616/users/raknop/SeeChange-rknop-dev-webap-install
          path: /global/cfs/cdirs/m2218/raknop/decat_wfd/rknop-dev-seechange-webap-install
          type: Directory
      - name: seechange-install
        hostPath:
          # path: /global/cfs/cdirs/m4616/users/raknop/PUT_THE_RIGHT_THING_HERE
          path: /global/cfs/cdirs/m2218/raknop/decat_wfd/rknop-dev-seechange-install
          type: Directory
      - name: seechange-archive-dir
        hostPath:
          # path: /global/cfs/cdirs/m4616/archive-rknop-dev
          path: /global/cfs/cdirs/m2218/decat-wfd/archive
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: webap
  namespace: ls4-rknop-dev
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-webap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webap-ingress
  namespace: ls4-rknop-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-rknop-dev-webap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webap
  namespace: ls4-rknop-dev
spec:
  rules:
  - host: webap.ls4-rknop-dev.production.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: webap-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: ls4-rknop-dev-webap.lbl.gov
    http:
      paths:
      - backend:
          service:
            name: webap-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ls4-rknop-dev-webap.lbl.gov
    secretName: ls4-rknop-dev-webap-cert
---
