apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webap-sessions-pvc
  namespace: ls4-rknop-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
  storageClassName: nfs-client
  volumeMode: Filesystem
