services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT:-8025}:8025

  make-archive-directories:
    image: rknop/upload-connector:${IMGTAG:-devshell}
    build:
      context: ../extern/nersc-upload-connector
      args:
        UID: 0
        GID: 0
    volumes:
      - type: volume
        source: devshell-archive-storage
        target: /storage
    entrypoint: bash -c "mkdir -p /storage/base && chown ${USERID:?err}:${GROUPID:?err} /storage/base && chmod a+rwx /storage/base"

  archive:
    depends_on:
      make-archive-directories:
        condition: service_completed_successfully
    image: rknop/upload-connector:${IMGTAG:-devshell}
    build:
      context: ../extern/nersc-upload-connector
      args:
        UID: 0
        GID: 0
    healthcheck:
      test: netcat -w 1 localhost 8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - CONNECTOR_READ_STORAGE=/storage_ro/base
      - CONNECTOR_WRITE_STORAGE=/storage/base
    volumes:
      - type: volume
        source: devshell-archive-storage
        target: /storage
      - type: volume
        source: devshell-archive-storage
        target: /storage_ro
        read_only: true
    secrets:
      - connector_tokens
    user: ${USERID:?err}:${GROUPID:?err}

  postgres:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange-postgres:${IMGTAG:-devshell}
    build:
      context: ../docker/postgres
    volumes:
      - seechange-devshell-postgres-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DATA_DIR: /var/lib/postgresql/data
      POSTGRES_PASSWORD: fragile
    healthcheck:
      test: netcat -w 1 localhost 5432 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5

  setuptables:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange:${IMGTAG:-devshell}
    build:
      context: ../
      dockerfile: ./docker/application/Dockerfile
      target: bindmount_code
    environment:
      SEECHANGE_CONFIG: /seechange/devshell/seechange_devshell.yaml
    depends_on:
      postgres:
         condition: service_healthy
    volumes:
      - type: bind
        source: ..
        target: /seechange
    working_dir: /seechange
    user: ${USERID:?err}:${GROUPID:?err}
    entrypoint: [ "alembic", "upgrade", "head" ]

  webap:
    depends_on:
      setuptables:
        condition: service_completed_successfully
      make-archive-directories:
        condition: service_completed_successfully
    image: gchr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange-webap:${IMGTAG:-devshell}
    build:
      context: ../webap
    user: ${USERID:-0}:${GROUPID:-0}
    ports:
      - "${WEBAP_PORT:-8081}:8081"
    healthcheck:
      test: netcat -w 1 localhost 8081
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - type: volume
        source: devshell-archive-storage
        target: /archive-storage
      - type: bind
        source: ../tests/webap_secrets
        target: /secrets
    entrypoint: [ "gunicorn", "-w", "4", "-b", "0.0.0.0:8081", "--timeout", "0", "seechange_webap:app" ]

  conductor:
    depends_on:
      setuptables:
        condition: service_completed_successfully
      mailhog:
        condition: service_started
    image: gchr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange_conductor:${IMGTAG:-devshell}
    build:
      context: ../
      dockerfile: ./docker/application/Dockerfile
      target: conductor
    user: ${USERID:?err}:${GROUPID:?err}
    ports:
      - "${CONDUCTOR_PORT:-8082}:8082"
    healthcheck:
      test: netcat -w 1 localhost 8082
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - type: volume
        source: conductor-sessions
        target: /sessions
    command: [ "./run_conductor.sh", "8082" ]
      
  make_data_dir:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange:${IMGTAG:-devshell}
    build:
      context: ../
      dockerfile: ./docker/application/Dockerfile
      target: bindmount_code
    volumes:
      - type: bind
        source: ..
        target: /seechange
    working_dir: /seechange
    user: ${USERID:?err}:${GROUPID:?err}
    entrypoint: bash -c "mkdir -p /seechange/devshell/temp_data"

  seechange:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange:${IMGTAG:-devshell}
    build:
      context: ../
      dockerfile: ./docker/application/Dockerfile
    environment:
      SEECHANGE_CONFIG: /seechange/devshell/seechange_devshell.yaml
      SEECHANGE_TEST_ARCHIVE_DIR: /archive_storage/base
    depends_on:
      setuptables:
        condition: service_completed_successfully
      archive:
        condition: service_healthy
      make_data_dir:
        condition: service_completed_successfully
      webap:
        condition: service_healthy
      conductor:
        condition: service_healthy
    volumes:
      - type: bind
        source: ..
        target: /seechange
      - type: volume
        source: devshell-archive-storage
        target: /archive_storage
    working_dir: /seechange
    user: ${USERID:?err}:${GROUPID:?err}
    entrypoint: [ "tail", "-f", "/etc/issue" ]

  seechange_nodb:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange:${IMGTAG:-devshell}
    build:
      context: ../
      dockerfile: ./docker/application/Dockerfile
      target: bindmount_code
    environment:
      SEECHANGE_CONFIG: /seechange/devshell/seechange_devshell.yaml
    depends_on:
      make_data_dir:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: ..
        target: /seechange
    working_dir: /seechange
    user: ${USERID:?err}:${GROUPID:?err}
    entrypoint: [ "tail", "-f", "/etc/issue" ]

  seechange_nomigrate:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-c3-time-domain}/seechange:${IMGTAG:-devshell}
    build:
      context: ../
      dockerfile: ./docker/application/Dockerfile
      target: bindmount_code
    environment:
      SEECHANGE_CONFIG: /seechange/devshell/seechange_devshell.yaml
    depends_on:
      postgres:
        condition: service_healthy
      make_data_dir:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: ..
        target: /seechange
    working_dir: /seechange
    user: ${USERID:?err}:${GROUPID:?err}
    entrypoint: [ "tail", "-f", "/etc/issue" ]

secrets:
  connector_tokens:
    file: ../tests/connector_tokens.txt

volumes:
  devshell-archive-storage:
  seechange-devshell-postgres-dbdata:
  conductor-sessions:
