name: Run Python Tests
on:
  push:
    branches:
      - main
      - docker
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  tests:
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Log into github container registry
#        uses: docker/login-action@v2
#        with:
#          registry: gchr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Pull or build images
        run: docker compose pull || (( docker compose build && docker compose push )

      - name: Run tests
        run: docker compose run runtests



#  seechange-postgres:
#    
#  build:
#    name: Run Python Tests
#    runs-on: ubuntu-latest
#
#    services:
#      postgres:
#        image: postgres
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#        ports:
#          - 5432:5432
#        # needed because the postgres container does not provide a
#        # healthcheck
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#      seechange-postgres:
#        image: 'docker/postgres/Dockerfile'
#        env:
#          POSTGRES_DATA_DIR: /var/lib/postgresql/data
#        ports:
#          - 5433:5432
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Python 3
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.8
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Run tests with pytest
#        env:
#          ZTF_USERNAME: ${{ secrets.ZTF_USERNAME }}
#          ZTF_PASSWORD: ${{ secrets.ZTF_PASSWORD }}
#
#        run: python -m pytest tests/
