name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: gchr.io
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      # - name: log into github container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: gchr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # I haven't yet figured out a way to get github actions to
      # pull from and push to a registry.  (I've tried a LOT
      # of different things, and have a forum question in.)
      #
      # So, for now, we have to rebuild the docker image every time
      # we run a test, which is profligate and slow, but it's what
      # we're stuck with for now.  At least running the tests on
      # your local checkout can be efficient.
      
      - name: run test
        run: |
          docker compose build
          docker compose run runtests
