name: Run Image Processing Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: bake
        uses: docker/bake-action@v2.3.0
        with:
          workdir: tests
          load: true
          files: docker-compose.yaml
          set: |
            archive.tags=gchr.io/${{ github.repository_owner }}/archive
            archive.cache-from=type=gha,scope=cached-archive
            archive.cache-to=type=gha,scope=cached-archive,mode=max
            postgres.tags=ghcr.io/${{ github.repository_owner }}/postgres
            postgres.cache-from=type=gha,scope=cached-postgres
            postgres.cache-to=type=gha,scope=cached-postgres,mode=max
            setuptables.tags=ghcr.io/${{ github.repository_owner }}/runtests
            setuptables.cache-from=type=gha,scope=cached-seechange
            setuptables.cache-to=type=gha,scope=cached-seechange,mode=max
            conductor.tags=gchr.io/${{ github.repository_owner }}/conductor
            conductor.cache-from=type=gha,scipe=cached-conductor
            conductor.cache-to=type=gha,scope=cached-conductor,mode=max
            webap.tags=gchr.io/${{ github.repository_owner }}/seechange-webap
            webap.cache-from=type=gha,scipe=cached-seechange-webap
            webap.cache-to=type=gha,scope=cached-seechange-webap,mode=max
            runtests.tags=ghcr.io/${{ github.repository_owner }}/runtests
            runtests.cache-from=type=gha,scope=cached-seechange
            runtests.cache-to=type=gha,scope=cached-seechange,mode=max
            shell.tags=ghcr.io/${{ github.repository_owner }}/runtests
            shell.cache-from=type=gha,scope=cached-seechange
            shell.cache-to=type=gha,scope=cached-seechange,mode=max

      - name: run test
        run: |
          # ref: https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          shopt -s nullglob
          TEST_SUBFOLDER=tests/improc docker compose run runtests
