name: Run Model Tests 2

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: log into github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup
        run: |
          # ref: https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: run test
        run: |
          shopt -s nullglob
          docker compose pull
          TEST_SUBFOLDER=$(ls tests/models/test_{m..z}*.py) docker compose run -e SKIP_BIG_MEMORY=1 runtests
