name: Run Python Tests
on:
  push:
    branches:
      - main
      - docker
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: gchr.io
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-seechange
          restore-keys: |
            ${{ runner.os }-buildx-
        
      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: gchr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push seechange-postgres docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/postgres
          push: true
          tags: gchr.io/${{ github.repository_owner }}/seechange-postgres
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix I found on discussions somewhere that avoids
      # buildx-cache growing out of hand
      # github.com/docker/build-push-action/issues/252
      # github.com/moby/buildkit/issues/1896
      - name: move buildx cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
      - name: build and push application docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/application
          push: true
          tags: gchr.io/${{ github.repository_owner }}/seechange
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          
      - name: move buildx cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
      - name: Run tests
        run: docker compose run runtests
