name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: gchr.io
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-seechange-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-seechange-

      - name: bake
        uses: docker/bake-action@v2.3.0
        with:
          workdir: tests
          load: true
          files: docker-compose-github.yaml
            
      - name: run test
        run: |
          docker compose run runtests

      # Do this to avoid the cache continuously growing
      - name: move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          
