name: Run Util Tests

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types: [completed]
  workflow_dispatch:

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: run tests in docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      COMPOSE_FILE: tests/docker-compose.yaml

    steps:
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup
        run: |
          # ref: https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: bake
        uses: docker/bake-action@v5
        with:
          workdir: tests
          load: true
          push: true
          files: docker-compose.yaml
          set: |
            archive.tags=ghcr.io/${{ github.repository_owner }}/archive
            archive.cache-from=type=gha,scope=cached-archive
            postgres.tags=ghcr.io/${{ github.repository_owner }}/postgres
            postgres.cache-from=type=gha,scope=cached-postgres
            setuptables.tags=ghcr.io/${{ github.repository_owner }}/runtests
            setuptables.cache-from=type=gha,scope=cached-seechange
            conductor.tags=ghcr.io/${{ github.repository_owner }}/conductor
            conductor.cache-from=type=gha,scipe=cached-conductor
            webap.tags=ghcr.io/${{ github.repository_owner }}/seechange-webap
            webap.cache-from=type=gha,scipe=cached-seechange-webap
            runtests.tags=ghcr.io/${{ github.repository_owner }}/runtests
            runtests.cache-from=type=gha,scope=cached-seechange
            shell.tags=ghcr.io/${{ github.repository_owner }}/runtests
            shell.cache-from=type=gha,scope=cached-seechange

      - name: run test
        run: |
          shopt -s nullglob
          TEST_SUBFOLDER=tests/util docker compose run -e SKIP_BIG_MEMORY=1 runtests
